@placeId = 60ad1c83d23f764d353a2fac
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFlMmUzOTE4MmRhYjRkNGZjOWIxM2EiLCJpYXQiOjE2MjIxMjUxNDUsImV4cCI6MTYyMjE2ODM0NX0.jeDkCgGyZ_lBb7a0MOaFEiLXOGWQyHY7pIQ10_1kdLc

@reviewId = 60aba6d3668dbe46d3794e5c

###

# Get ALL places
GET http://localhost:4000/api/places

###

# Search a place
GET http://localhost:4000/api/places/search?name=London

###

# Get ONE place
GET http://localhost:4000/api/places/{{placeId}}

###

# Create a place
POST http://localhost:4000/api/places
Authorization: Bearer {{userToken}}
content-type: application/json

{
  "name": "Brick Lane",
  "image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3UGZbVXx2yO6DqG6ldrwN6A57zp8Z6u_T4A&usqp=CAU",
  "description": " It's a cool place",
  "area": "Shoreditch",
  "address": "Brick Lane",
  "postcode": "E1 6QL",
  "lat": 123,
  "long": 321,
  "categories": [
    "shopping", "coffee shops"
    ],
  "rating": 5
}

### Delete a place

DELETE http://localhost:4000/api/places/{{placeId}}
Authorization: Bearer {{userToken}}



### Update a place
PUT http://localhost:4000/api/places/{{placeId}}
Authorization: Bearer {{userToken}}
Content-Type: application/json


  {
    "categories": [],
    "name": "London1",
    "description": "a very dangerous place",
    "area": "shepard bush",
    "address": ".....",
    "postcode": "stop asking questions",
    "lat": 2,
    "long": 2,
    "rating": 5,
    "__v": 0
  }


###

# USERS 

POST http://localhost:4000/api/register
content-type: application/json

{
  "username": "gsr",
  "password": "gsr",
  "passwordConfirmation": "gsr",
  "email":"gsr@gsr16",
  "emailConfirmation": "gsr@gsr16"

  }


###

POST http://localhost:4000/api/login
content-type: application/json

{
  "email":"gsr@gsr16",
  "password": "gsr"
  }

###

# REVIEWS

# Post a review
POST http://localhost:4000/api/places/{{placeId}}/review
content-type: application/json
Authorization: Bearer {{userToken}}

{
  "text": "So beautiful!!!!"
}

###

PUT http://localhost:4000/api/places/{{placeId}}/review/{{reviewId}}
content-type: application/json
Authorization: Bearer {{userToken}}

{
  "text": "third 1"
}

### Add place to MyFav
POST  http://localhost:4000/api/favourites/{{placeId}}
content-type: application/json
Authorization: Bearer {{userToken}}

{
  "favourites": []
}
