@placeId = 60a95e969d05563081a3b67c

###

# Get ALL places
GET http://localhost:4000/api/places

###
GET http://localhost:4000/api/places/{{placeId}}

###
PUT http://localhost:4000/api/places/60aa588cb8353a1bd4e6203d
Content-Type: application/json

[
  {
    "categories": [],
    "name": "London1",
    "description": "a very dangerous place",
    "area": "shepard bush",
    "address": ".....",
    "postcode": "stop asking questions",
    "lat": 2,
    "long": 2,
    "rating": 5,
    "__v": 0
  }
]

# Search a place
GET http://localhost:4000/api/places/search?name=London

###

# Get ONE place
GET http://localhost:4000/api/places/{{placeId}}

###

POST http://localhost:4000/api/register
content-type: application/json

{
  "username": "lari1",
  "password": "lari1",
  "email":"lari1@lari16"
  }

###

  POST http://localhost:4000/api/login
content-type: application/json

{
  "email":"lari1@lari16",
  "password": "lari1"
  }
